version: "3.0"
services:
  redis:
    image: "redis:5.0.6-alpine"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./OPAL.Nginx
    ports:
      - '5000:80'
  client:
    build:
      dockerfile: Dockerfile.Presentation.dev
      context: .
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '5001:80'
  api:
    build:
      dockerfile: Dockerfile.Service.dev
      context: .
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '5002:80'
