FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY ./OPAL2/OPAL.sln ./
COPY ./OPAL2/OPAL.Presentation/OPAL.Presentation.csproj ./OPAL.Presentation/
COPY ./OPAL2/OPAL.Domain/OPAL.Domain.csproj ./OPAL.Domain/
COPY ./OPAL2/OPAL.Service/OPAL.Service.csproj  ./OPAL.Service/
COPY ./OPAL2/OPAL.Application/OPAL.Application.csproj ./OPAL.Application/
COPY ./OPAL2/OPAL.Search/OPAL.Search.csproj ./OPAL.Search/
RUN dotnet restore

# copy everything else and build app
COPY ./OPAL2/ ./

WORKDIR /app
RUN dotnet publish -c Release -o out ./OPAL.sln

FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 AS runtime
WORKDIR /app
COPY --from=build /app/out ./
ENTRYPOINT ["dotnet", "OPAL.Presentation.dll"]
